version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=lc-maintenance-db
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  mysql:
    image: mysql:8
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: lc-maintenance-db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./lc-maintenance-db.sql:/docker-entrypoint-initdb.d/lc-maintenance-db.sql
    networks:
      - app-network
    ports:
      - "3310:3306"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
